[package]
name = "intention-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
futures-util = "0.3.31"
intention-config = { path = "../intention-config", version = "=0.0.0" }
intention-domain = { path = "../intention-domain", version = "=0.0.0" }
intention-model = { path = "../intention-model", version = "=0.0.0" }
intention-storage = { path = "../intention-storage", version = "=0.0.0" }
intention-types = { path = "../intention-types", version = "=0.0.0" }

[dev-dependencies]
futures-executor = "0.3.31"
