[package]
name = "intention-test-support"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
intention = { path = "../intention", version = "=0.0.0", features = ["test-support"] }
intention-config = { path = "../intention-config", version = "=0.0.0" }
intention-daemon = { path = "../intention-daemon", version = "=0.0.0", features = ["test-support"] }
intention-domain = { path = "../intention-domain", version = "=0.0.0" }
intention-protocol = { path = "../intention-protocol", version = "=0.0.0" }
intention-transport = { path = "../intention-transport", version = "=0.0.0" }
intention-types = { path = "../intention-types", version = "=0.0.0" }
serde_json = "1.0.149"
tempfile = "3.24.0"
