[package]
name = "intention-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
intention-client = { path = "../intention-client", version = "=0.0.0" }
intention-protocol = { path = "../intention-protocol", version = "=0.0.0" }
intention-types = { path = "../intention-types", version = "=0.0.0" }

[dev-dependencies]
intention-daemon = { path = "../intention-daemon", version = "=0.0.0" }
intention-domain = { path = "../intention-domain", version = "=0.0.0" }
intention-transport = { path = "../intention-transport", version = "=0.0.0" }
