[package]
name = "intention-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
fs4 = { version = "1.1.0", features = ["sync"] }
intention-domain = { path = "../intention-domain", version = "=0.0.0" }
intention-protocol = { path = "../intention-protocol", version = "=0.0.0" }
intention-transport = { path = "../intention-transport", version = "=0.0.0" }
intention-types = { path = "../intention-types", version = "=0.0.0" }
tokio = { version = "1.53.1", features = ["rt", "time"] }

[dev-dependencies]
tempfile = "3.24.0"
