[package]
name = "intention-daemon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
intention = { path = "../intention", version = "=0.0.0" }
intention-protocol = { path = "../intention-protocol", version = "=0.0.0" }
intention-transport = { path = "../intention-transport", version = "=0.0.0" }
intention-types = { path = "../intention-types", version = "=0.0.0" }
