[package]
name = "intention-storage-sqlite"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
intention-config = { path = "../intention-config", version = "=0.0.0" }
intention-domain = { path = "../intention-domain", version = "=0.0.0" }
intention-storage = { path = "../intention-storage", version = "=0.0.0" }
intention-types = { path = "../intention-types", version = "=0.0.0" }
sqlite = { package = "rusqlite", version = "0.40.2", features = ["bundled"] }
rusqlite_migration = "2.6.0"
serde_json = "1.0.149"

[dev-dependencies]
tempfile = "3.24.0"
